
env:
  - version=2.1
language: java
jdk:
  - oraclejdk8
group: edge
before_script:
  - gradle --version
  - wget https://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip -d . gradle-3.5-bin.zip
  - export PATH=$PATH:./gradle-3.5/bin
  - ./gradle-3.5/bin/gradle --version
script:
  - ./gradle-3.5/bin/gradle buildJar
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: "$GITHUB_API_TOKEN"
  file: "./build/lib/rkms-$version.jar"
  skip_cleanup: true
  on:
    repo: zVolt/rkm-desktop
